# Course Assessment {-}

Assessment is a process of reasoning from evidence that you provide in the work that you do on tasks in relation to the outcomes of the course. Ultimately, you need to demonstrate to me that you have met the outcomes listed on the syllabus. In a course *about* social media and personal learning networks, that means you will have to demonstrate to me in your activities and in your reflections on those activities that you have, in one way or another, met the intended outcomes. Doing your work with that in mind will absolutely help you perform in the course. It also means that you will have to make your personal learning network interactions *visible* to me and to your fellow learners in the course.

The way to do that is to `tag` your work in whatever platform you are interacting with `edci338`. The work you do will happen in two primary locations and some other secondary locations. Please see the [Course Toolset](https://cmadland.github.io/edci338-202201/course-toolset) for more details.

The fundamental and core task in this course is for you to build and reflect on a *Personal Learning Network (PLN)* using modern networked tools. Your PLN will likely end up with two *nodes* by the time the course is complete. One node will be the network we build within this community of learners, while the other node (or maybe more) will be the professional connections you make outside the course. Hopefully, both nodes will persist beyond the end of the course, which is why it is critical that the work you do is NOT locked up in an institutional Learning Management System (LMS; Brightspace is the UVic LMS).

## Building Community Support {-}

This is an asynchronous online course, meaning that we don't have any specific *required* meeting times. This can be a significant advantage for those who unable to meet at a particular time on in a particular place, but it can also contribute to challenges completing the coursework for those who prefer to work in more social contexts. We seek to strike a balance between learners working in isolation, and requiring on-campus meetings. To do this, there are three critical structures in the course: learning pods, weekly meetings, and assessment meetings with me.

### Learning Pods {-}

You will be provided a link to a password-protected page where you can sign up for a learning pod, which is a group of 3-4 learners who meet together regularly (ideally weekly) at a time that works for them. This time should be used to review the course materials and any questions that learners might have, and also to plan and organize work on the course assignments. Learning pods are intended to be your first line of support during the course.

### Weekly Meetings {-}

We will determine a time during the week that works for as many people as possible for a 1-hour meeting time with me. This meeting will not be *required*, but it is strongly recommended that you attend as many of these meetings as you are able. This will be a time to discuss the week's readings, clarify questions about both the content and the logistics (what is due when and where) of the course.

### Assessment Meetings {-}

Each learning pod will be required to meet with me at least twice during the course. The first time will be within the first two weeks to ensure that you have been able to get set up with all the required tools and connected with a learning pod. The second required time will be prior to reading week to ensure that you are on track for the Major Project. Learning pods are also encouraged to book meeting times with me as needed.

## Community Contributions and Connections (30%){-}

Throughout the course, you will be required to reflect on the work you are doing in relation to the topics of that particular week. This reflection will be in the form of blog posts on your own blog (either on opened.ca, or another blogging platform) and they will be due throughout the course. There are 8 prompts for you in the course and you will be required to respond to each of those. You will choose 2 to be assessed for grading as `showcase` posts (15% each for a total of 30%). Your 2 showcase posts will be polished for publication on your blog and should reflect a professional *voice*.

### Post Prompts (Reviewed in your Learning Pods) {-}

Your posts in response to each of the prompts will be in the form of one 'Wow' and one 'Wonder'. A Wow is anything from the week that caught your interest from the readings, videos, tasks, your PLN, or one of your fellow learners' posts. It should be something that you haven't thought of before or maybe that you have changed your thinking about. A Wonder is something that you have a question about from the same sources. It might be something you thought wasn't explained clearly, something that is counter-intuitive, doesn't make sense, is muddy, or simply something you want to investigate further. Your Wow and Wonder posts can be brief (100-150 words) and in point form, but they must include a hyperlink to the artifact you are writing about and a brief reflection on why you chose that Wow or Wonder.

### Showcase Posts (2 @ 15% each) {-}

You will choose 2 of your Wow and Wonder posts and expand and polish them to be about 500 words. You should reference course artifacts **and** find resources not listed in the syllabus to inform and support your thinking about your Wows and Wonders.

Set a goal for yourself of linking to at least 2 other learners in each showcase post. You are encouraged to diversify your interaction and reading of other learners in the community. You should find that these interactions lead to increased traffic on your own blog, which will provide opportunities to have your thinking supported, questions answered, and possibly new connections made.

It is recommended that you comment on others' posts by including a link in your own post to the post you are commenting on. This will create a 'trackback' on the original post, which is just like a comment. Make sure you check the comments on your own site because you will have to approve them before they are visible. You will see a notification in the side menu of WordPress when you have comments that need to be approved.

Each Showcase post should:

- be about 500 words in length,  
- include a featured image,  
- include hyperlinks to relevant course materials and activities,  
- include commentary on and hyperlinks to other EDCI338 learners' posts,  
- a list of references including hyperlinks to cited work (use the style you are accustomed to)  

### Suggested Prompts for Comments{-}

Please remember that these blogs are shared publicly, as are your comments. It is important to use your comments as a way to provide supportive, constructive feedback, to initiate a conversation, or to share connections. Keep your language positive, offer suggestions, and focus on the content of the blog post - discourse is encouraged.

Examples of positive engagement include:

- My new thinking after reading your post is...  
- I agree with the idea of... because...  
- I am wondering if you have read this article/website/book (share a resource link)  
- I noticed that our thinking differs in this way...  
- A connection I made between your work and...is...  
- I really liked how you explained...and I am wondering if you can tell me more about...  
- Something I am wondering after reading your post is...  

## Major Project (40%){-}

You will be working on the major project throughout the course and in collaboration with both a learning pod and also with the whole class. The end result of this work will be a polished e-book of resources for educators who want to learn about social media and building a PLN. For this project, you will be working in Learning Pods, a group of 3-4 learners working together to help each other succeed. Each Learning Pod will be responsible for researching and publishing resources about one social media tool that educators might use in their teaching. There is a preliminary list of tools on the [toolset](/course-toolset) page.

The platform we will use to create the resource will be GitHub, a tool specifically designed to enable remote teams to collaborate on complex projects. Git, the software that enables GitHub, was designed to aid the development of the Linux operating system. We will spend some time early in the course becoming familiar with GitHub and the terminology it uses. While this may sound intimidating, it is well within your capabilities to learn to use it. One thing you need to know about GitHub is that it makes everyone's contributions visible to the whole community. We will all be working in the same space, and everyone in the class will be able to see what everyone else has contributed.

### Project Details {-}

You will work in your learning pods to complete the major project, which will be to create an online resource for educators wishing to learn about using social media tools to build a Personal Learning Network. Each Learning Pod will contribute an in-depth analysis of one networking tool that might be used in educational settings. The structure of each page in the resource will follow the topics and structure of the course, so you will be working on completing the major project as you progress through the course.

## Celebration of Learning (30%) {-}

Your final task in the course will be to tell me what you have learned. This will be one final post published on your blog in which you reflect on **each** of the course outcomes and how your work in the course contributed to meeting those outcomes. 

Your reflection must include references and hyperlinks to:  
- *your own work* in the course and an explanation of how your thinking was formed,  
- *your colleagues' work* in the course and an explanation of how their work informed your thinking,  
- *course materials*, including articles, videos, interviews, social media artifacts, etc.   

```{block, type='protip'}
#### ✨ ProTip{-}
**I STRONGLY recommend that you create this post as a draft at the beginning of the course and add to it throughout the course as we progress. It will be much more difficult to complete this post if you leave it until the end.**  

An easy way to help yourself manage this is to create a set of outcome categories on your blog (outcome1, outcome2, etc) and apply those categories to the posts that meet those outcomes.
```
## Grading Standards {-}

[Click here to read about the SOLO Taxonomy.](https://teaching.madland.ca/solo)
