# Course Toolset {-}

We will use a variety of tools in this course, as you might expect in a course about personal learning networks and using social media in education. One of the primary reasons for that is to allow opportunity for you to make your learning visible and to share it with the community, whatever that might look like for you. I recognize that you may be coming to this course for a variety of reasons, including as an elective for your Teacher Education program, but also as an elective in another program, for your own personal learning, or maybe because you heard about the series of courses that [edtechuvic](https://twitter.com/edtechuvic) offers.

## WordPress {-} 

WordPress will be our hub for EDCI338. [The course hub](https://edtechuvic.ca/edci338) is where I will post updates throughout the course and you are strongly encouraged to subscribe to receive notifications of updates using an email address that you often check. 

Additionally, you will sign up for and create your own WordPress site. It is on this site that you will publish your reflections on your work through the course. We have provided instructions for how to get set up on [opened.ca](https://opened.ca). You may already have an ___.opened.ca website that you created for another EDCI course and you may use that one by simply adding an `edci338` category to your posts. You may also use your own site through WordPress.com or another blogging tool, as long as the site publishes an RSS feed. The main caveat is that my ability to help troubleshoot your site may be more limited if you aren't on opened.ca.



## An RSS Reader