# Course Assessment {-}

Assessment is a process of reasoning from evidence that you provide in the work that you do on tasks in relation to the outcomes of the course. Ultimately, you need to demonstrate to me that you have met the outcomes listed on the syllabus. In a course *about* social media and personal learning networks, that means you will have to demonstrate to me in your activities and in your reflections on those activities that you have, in one way or another, met the intended outcomes. Doing your work with that in mind will absolutely help you perform in the course. It also means that you will have to make your personal learning network interactions *visible* to me and to your fellow learners in the course.

The way to do that is to `tag` your work in whatever platform you are interacting with `edci338`. The work you do will happen in two primary locations and some other secondary locations. Please see the [Course Toolset](https://cmadland.github.io/edci338-202201/course-toolset) for more details.

The fundamental and core task in this course is for you to build and reflect on a *Personal Learning Network (PLN)* using modern networked tools. Your PLN will likely end up with two *nodes* by the time the course is complete. One node will be the network we build within this community of learners, while the other node (or maybe more) will be the professional connections you make outside the course. Hopefully, both nodes will persist beyond the end of the course, which is why it is critical that the work you do is NOT locked up in an institutional Learning Management System (LMS; Brightspace is the UVic LMS).

## Community Contributions and Connections (30%){-}

Throughout the course, you will be required to reflect on the work you are doing in relation to the topics of that particular week. This reflection will be in the form of blog posts on your own blog (either on opened.ca, or another blogging platform) and they will be due throughout the course. There are 11 prompts for you in the course and you will be required to respond to 6 of those (you may choose to respond to more, but 6 are required). Of the 6 posts you publish, you will choose 2 to be assessed for grading as `showcase` posts (15% each for a total of 30%). Your 6 posts should be considered `work-in-progress (WIP)`. Your 2 showcase posts will be polished for publication on your blog and should reflect a professional *voice*.

You are encouraged to initiate your own posts in response to the materials and resources shared throughout the course, as well as linking out to materials and literature to support your thinking. These resources will be provided in the form of multimedia video, social media links, and reading links that are all available through the University of Victoria library.

In addition to authoring blog posts, you will be expected to contribute to the edci338 community by commenting on the posts of your peers. Review the blog feed for your section, select posts of interest and provide feedback or ask questions of other authors.

Set a goal for yourself of interacting with at least 2 other bloggers after a posted assignment. You are encouraged to diversify your interaction and reading of other learners in the community. You should find that these interactions lead to increased traffic on your own blog, which will provide opportunities to have your thinking supported, questions to answer, and possibly new connections made.

It is recommended that you comment on others' posts by creating a new post on your own site and including a link to the post you are commenting on. This will create a 'trackback' on the original post, which is just like a comment. Make sure you check the comments on your own site because you will have to approve them before they are visible. You will see a notification in the side menu of WordPress when you have comments that need to be approved.

Each post should:

- be 400-500 words in length,  
- include a featured image,  
- include hyperlinks to relevant course materials and activities,  
- include commentary on and hyperlinks to other EDCI338 learners' posts,  
- hyperlinks to cited work (use the style you are accustomed to)  

### Suggested Prompts for Comments{-}

Please remember that these blogs are shared publicly, as are your comments. It is important to use your comments as a way to provide supportive, constructive feedback, to initiate a conversation, or to share connections. Keep your language positive, offer suggestions, and focus on the content of the blog post - discourse is encouraged.

Examples of positive engagement include:

- My new thinking after reading your post is...  
- I agree with the idea of... because...  
- I am wondering if you have read this article/website/book (share a resource link)  
- I noticed that our thinking differs in this way...  
- A connection I made between your work and...is...  
- I really liked how you explained...and I am wondering if you can tell me more about...  
- Something I am wondering after reading your post is...  

## Major Project (40%){-}

You will be working on the major project throughout the course and in collaboration with both a learning pod and also with the whole class. The end result of this work will be a polished e-book of resources for educators who want to learn about social media and building a PLN. For this project, you will be working in Learning Pods, a group of 3-4 learners working together to help each other succeed. Each Learning Pod will be responsible for researching and publishing resources about one social media tool that educators might use in their teaching. There is a preliminary list of tools on the [toolset](/course-toolset) page.

The platform we will use to create the resource will be GitHub, a tool specifically designed to enable remote teams to collaborate on complex projects. Git, the software that enables GitHub, was designed to aid the development of the Linux operating system. We will spend some time early in the course becoming familiar with GitHub and the terminology it uses. While this may sound intimidating, it is well within your capabilities to learn to use it. One thing you need to know about GitHub is that it makes everyone's contributions visible to the whole community. We will all be working in the same space, and everyone in the class will be able to see what everyone else has contributed.

## Celebration of Learning (30%) {-}

Your final task in the course will be to tell me what you have learned. This will be one final post published on your blog in which you reflect on **each** of the course outcomes and how your work in the course contributed to meeting those outcomes. 

Your reflection must include references and hyperlinks to:  
- *your own work* in the course and an explanation of how your thinking was formed,  
- *your colleagues' work* in the course and an explanation of how their work informed your thinking,  
- *course materials*, including articles, videos, interviews, social media artifacts, etc.   

```{block, type='protip'}
#### ✨ ProTip{-}
**I STRONGLY recommend that you create this post as a draft at the beginning of the course and add to it throughout the course as we progress. It will be much more difficult to complete this post if you leave it until the end.**  

An easy way to help yourself manage this is to create a set of outcome categories on your blog (outcome1, outcome2, etc) and apply those categories to the posts that meet those outcomes.
```
